language: python
python:
   - "3.6"

# command to install dependencies
install:
  - pip install -r requirement.txt
  - pip install coverage codev
  - pip install nose

# Run tests
script:
    - nosetests --with-coverage --cover-package=app

after_success:
  - coveralls
  - codecov --token=tV3mvYU0pYLiaSevCdUmTNgdFdbSEGWi7
